package api

import (
	"fmt"
	"net/http"
	"strings"
)

// InstallScriptHandler serves a self-contained bash installer at GET /install.sh
// The script auto-detects OS/arch, downloads the quicktunnel binary from this
// same server, and immediately joins the requested network.
//
// Client usage (one-liner, no files needed):
//
//	curl http://<server>/install.sh | sudo bash -s -- <network_id> <api_key>
//	curl http://<server>/install.sh | sudo bash -s -- <network_id> <api_key> [device_name]
type InstallScriptHandler struct {
	// serverURL is the public base URL of this server, e.g. "http://54.89.232.16:3000"
	// It is embedded into the generated script so the script knows where to pull the binary from.
	serverURL string
}

// NewInstallScriptHandler creates a handler that embeds serverURL into the script.
// Pass the PUBLIC_SERVER_URL env value (or the listen address as fallback).
func NewInstallScriptHandler(serverURL string) *InstallScriptHandler {
	return &InstallScriptHandler{
		serverURL: strings.TrimRight(strings.TrimSpace(serverURL), "/"),
	}
}

// ServeScript handles GET /install.sh
func (h *InstallScriptHandler) ServeScript(w http.ResponseWriter, r *http.Request) {
	// Derive server URL: prefer the value baked in at startup; fall back to the
	// Host header so the script points back to the same address the user hit.
	serverURL := h.serverURL
	if serverURL == "" {
		scheme := "http"
		if r.TLS != nil {
			scheme = "https"
		}
		serverURL = fmt.Sprintf("%s://%s", scheme, r.Host)
	}

	script := buildInstallScript(serverURL)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "inline; filename=install.sh")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(script))
}

// buildInstallScript returns the bash script with the server URL embedded.
func buildInstallScript(serverURL string) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
# QuickTunnel — one-line network join script
# Generated by: %s/install.sh
#
# Usage:
#   curl %s/install.sh | sudo bash -s -- <network_id> <api_key> [device_name]
#
# Example (API key from dashboard "Client setup details"):
#   curl %s/install.sh | sudo bash -s -- 5agrlxob7exh 9c4014e481... mypc
#
set -euo pipefail

SERVER_URL="%s"
NETWORK_ID="${1:-}"
API_KEY="${2:-}"
DEVICE_NAME="${3:-}"

# ── Validate arguments ─────────────────────────────────────────────────────────
if [ -z "$NETWORK_ID" ] || [ -z "$API_KEY" ]; then
  echo "Usage: curl $SERVER_URL/install.sh | sudo bash -s -- <network_id> <api_key> [device_name]"
  echo ""
  echo "  network_id   — copy from the dashboard Network page"
  echo "  api_key      — copy from 'Client setup details' on the dashboard"
  echo "  device_name  — optional, e.g. mypc  (defaults to hostname)"
  exit 1
fi

if [ -z "$DEVICE_NAME" ]; then
  DEVICE_NAME="$(hostname 2>/dev/null || echo unknown-device)"
fi

# ── Detect OS / arch ───────────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH_RAW="$(uname -m)"
case "$ARCH_RAW" in
  x86_64)  ARCH="amd64"  ;;
  aarch64) ARCH="arm64"  ;;
  armv7*)  ARCH="armv7"  ;;
  arm*)    ARCH="armv7"  ;;
  *)
    echo "Unsupported architecture: $ARCH_RAW"
    exit 1
    ;;
esac

case "$OS" in
  linux|darwin) ;;
  *)
    echo "Unsupported OS: $OS"
    exit 1
    ;;
esac

echo "Detected: $OS / $ARCH"

# ── Download binary ────────────────────────────────────────────────────────────
BINARY_URL="$SERVER_URL/api/v1/downloads/client/$OS/$ARCH"
BINARY_PATH="/usr/local/bin/quicktunnel"

echo "Downloading quicktunnel from $BINARY_URL ..."
if command -v curl &>/dev/null; then
  curl -fsSL "$BINARY_URL" -o "$BINARY_PATH"
elif command -v wget &>/dev/null; then
  wget -qO "$BINARY_PATH" "$BINARY_URL"
else
  echo "Error: curl or wget is required"
  exit 1
fi
chmod +x "$BINARY_PATH"
echo "Installed: $BINARY_PATH"

# ── Join the network ───────────────────────────────────────────────────────────
echo "Joining network $NETWORK_ID as '$DEVICE_NAME' ..."
exec "$BINARY_PATH" join \
  --server  "$SERVER_URL" \
  --network "$NETWORK_ID" \
  --api-key "$API_KEY" \
  --name    "$DEVICE_NAME"
`, serverURL, serverURL, serverURL, serverURL)
}
